# Generated by Django 5.2.12 on 2026-03-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptNova', '0002_user_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, default='', max_length=1000)),
                ('tone', models.CharField(blank=True, default='', max_length=100)),
                ('length_preference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=600, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='ScriptNova.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
