# Generated by Django 5.2.12 on 2026-04-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptNova', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='prompt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
