# Generated by Django 5.2.12 on 2026-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptNova', '0004_blog_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.AddField(
            model_name='blog',
            name='favourite',
            field=models.CharField(choices=[('normal', 'Normal'), ('favourite', 'Favourite')], default='normal', max_length=20),
        ),
    ]
