# Generated by Django 5.2.12 on 2026-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptNova', '0005_remove_blog_status_blog_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='humanized_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
