# Generated by Django 6.0.5 on 2026-06-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptNova', '0009_blogcomment_blogreaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reader_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reader_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogreaction',
            name='reader_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogreaction',
            name='reader_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to='ScriptNova.user'),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_reactions', to='ScriptNova.user'),
        ),
    ]
